# Change these first
owner: azuma-healthtech-public # Your GitHub organization or username, where this repository lives
repo: uptime-prd # The name of this repository

sites:
  - name: "azuma: API"
    url: https://azuma-health.tech/health/doa-gateway
  - name: "azuma: Zero Trust Gateway"
    url: https://azuma-health.tech/health/gateway
  - name: "azuma doa: Identity Service"
    url: https://azuma-health.tech/health/doa-idp
  - name: "azuma doa: Permissions & Access Control"
    url: https://azuma-health.tech/health/doa-acl
  - name: "azuma doa: OAuth 2.0 and OpenID Connect Provider"
    url: https://azuma-health.tech/health/doa-oidc
  - name: "azuma doa: Tenant & Organization Service"
    url: https://azuma-health.tech/health/doa-organization
  - name: "azuma doa: Administration Service"
    url: https://azuma-health.tech/health/doa-admin
  - name: "azuma doa: Mailing Service"
    url: https://azuma-health.tech/health/doa-mailing

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.azuma-health.tech
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/azuma-healthtech/uptime-prd/master/assets/logo-1.svg
  name: azuma status
  introTitle: "**azuma** status"
  introMessage: This is an overview page, which uses **real-time** data to display live service status, maintenance windows as well as active and past incidents.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
